### ISSUE TITLE
Bug and questions

### ISSUE THREAD

**Issue by Kasia1403** [Gilded-Games/The-Aether-II#175]
Bug : Minecraft 1.12.2 Aether II 0.3.0  Can't open inventory gui. Could You add a keybind for that ? And second question : When will be next update for Minecraft 1.12.2 ? The mod looks still as beta or even alpha.

**Comment by Kasia1403** [comment]
Whyyy nobody answers ? 😞😭

**Comment by bconlon1** [comment]
This isn't really the place to ask questions, you can ask questions on our [Discord](https://discord.gg/aethermod) or our [CurseForge](https://www.curseforge.com/minecraft/mc-mods/aether-ii) page.

The inventory GUI will likely have a keybind in the future. The next update will be on 1.19 as we don't plan to release anymore updates on 1.12, we're going straight to porting the mod from 1.12 to 1.19 after we finish porting Aether I from 1.12 to 1.19. Because of this, we can't predict when the next update will be.

**Comment by Kasia1403** [comment]
Could You at least promise me that You will make an update for 1.12.2 when You will finish porting to 1.19 ? Please ! I'm disabled and bored.

**Comment by bconlon1** [comment]
We'll have to rewrite the mod when we put it on 1.19 so we cannot go back to 1.12 afterwards, we don't have the developer resources to work on versions outside the latest.
