### ISSUE TITLE
Feature: The Great Aether Merge

### ISSUE THREAD

**Issue by neverdestroyer23** [Gilded-Games/The-Aether-II#183]
The Aether in Aether I is basically just floating islands with skyroot trees on them.

Now, I have a proposition.

Merge both Aethers.
Yeah, that's it. Sure, this would probably just some rebranding and porting. (Which I know is hard) And will probably delay this mod's development for 3-4 months.
But it can be done.

**Comment by darksonic300** [comment]
I don't really see why they should merge at all.
Aether II in itself is supposed to be a continuation and improvement of the original in a modern view altogether.
Aether I instead is what it has been since the beta days, and is maintained to be as it was back in the day, so merging the two would literally mean to just stop working on Aether I.
Also Aether I is already receiving some extra content from Aether II's GoTV as the Genesis Addon.

**Comment by MarvelMPH** [comment]
Why? As far as I am aware aether 1 is preserved for legacy purposes and most of its contents are going to be available in aether 2 so merging them seems redundant.

**Comment by OzPayn** [comment]
While I think this request is well-meaning, it is slightly misguided given the reason for separating Aether 1 from Aether II in the first place.

Aether 1 has been separated from Aether II and maintained as an independent mod project specifically because of an overwhelming community demand for the original mod's content and features to be preserved and maintained _specifically without_ the changes made in Aether II. So merging the two projects into one mod would just start demands for the classic mod to be revived once again.

Functionally, I think our plans with Aether II likely will achieve what you're looking for anyway, Aether II will contain a lot of the content of the original mod (though remade and reworked to fit the new design ideas and aesthetics) and the two mods will be compatible for players that want both content sets (even with some discussion over ways of making their compatibility even more integrated than simply functioning alongside each other)

We also have an add-on project (and more planned) for Aether 1 that re-adds a lot of older Aether II content _as an optional add-on_ which means the original experience is preserved while still allowing for some expansion and enhancements for players that want more content.

So yeah I'm closing this issue as we do not have plans to merge the two projects into a single project/download, but we are going to be offering integration, compatibility, and add-ons that functionally achieve the result you're looking for anyway.
