### ISSUE TITLE
Feature: Basic terrain

### ISSUE THREAD

**Issue by OzPayn** [Gilded-Games/The-Aether-II#188]
porting over Aether 1 might be fine to start with
I'll get round to posting some examples and sketches that I feel may be appropriate for reference but honestly I think starting with Aether 1's terrain is gonna be a good first step

**Comment by Jonathing** [comment]
Food for thought: It might be wise to consider the implementation details for whatever your end goal for terrain generation is. If you want the final product to be more continental-like rather than sparse islands, then porting over Aether I's terrain generation in its entirety might not be the best idea.
